<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
	<UseWPF>true</UseWPF>
	<OutputType>Exe</OutputType>
    <StartupObject></StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="gsdll64.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="gsdll64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TBird.Core\TBird.Core.csproj" />
  </ItemGroup>

</Project>
