// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeAnalyzer.Data;

#nullable disable

namespace TradeAnalyzer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.BacktestResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("ExitDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExitPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("ExitReason")
                        .HasColumnType("TEXT");

                    b.Property<double>("Return")
                        .HasColumnType("REAL");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("BacktestResults");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.BacktestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgReturn")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("InSampleEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InSampleStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OutSampleEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OutSampleStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WinRate")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.DailyBar", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjClose")
                        .HasColumnType("REAL");

                    b.Property<double?>("AdjHigh")
                        .HasColumnType("REAL");

                    b.Property<double?>("AdjLow")
                        .HasColumnType("REAL");

                    b.Property<double?>("AdjOpen")
                        .HasColumnType("REAL");

                    b.Property<double?>("AdjVolume")
                        .HasColumnType("REAL");

                    b.Property<double?>("AdjustmentFactor")
                        .HasColumnType("REAL");

                    b.Property<double?>("Close")
                        .HasColumnType("REAL");

                    b.Property<double?>("High")
                        .HasColumnType("REAL");

                    b.Property<double?>("Low")
                        .HasColumnType("REAL");

                    b.Property<double?>("Open")
                        .HasColumnType("REAL");

                    b.Property<double?>("TurnoverValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Code", "Date");

                    b.HasIndex("Date");

                    b.HasIndex("Code", "Date");

                    b.ToTable("DailyBars");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.EarningsCalendar", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalQuarter")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalYear")
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "Date");

                    b.ToTable("EarningsCalendars");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.EdinetDocument", b =>
                {
                    b.Property<string>("DocId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CsvFlag")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocTypeCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("EdinetCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Parsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecCode")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SubmitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("XbrlFlag")
                        .HasColumnType("TEXT");

                    b.HasKey("DocId");

                    b.HasIndex("SubmitDate");

                    b.HasIndex("NormalizedCode", "SubmitDate");

                    b.ToTable("EdinetDocuments");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.EdinetFinFact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConsolidated")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Code", "FactName");

                    b.HasIndex("DocId", "ElementId");

                    b.ToTable("EdinetFinFacts");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.FinSummary", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DiscloseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Bps")
                        .HasColumnType("REAL");

                    b.Property<double?>("Eps")
                        .HasColumnType("REAL");

                    b.Property<double?>("Equity")
                        .HasColumnType("REAL");

                    b.Property<double?>("NetProfit")
                        .HasColumnType("REAL");

                    b.Property<double?>("OperatingProfit")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sales")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalAssets")
                        .HasColumnType("REAL");

                    b.HasKey("Code", "DiscloseDate", "DocType");

                    b.HasIndex("Code", "DiscloseDate");

                    b.ToTable("FinSummaries");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.Signal", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rationale")
                        .HasColumnType("TEXT");

                    b.Property<double>("RuleScore")
                        .HasColumnType("REAL");

                    b.HasKey("Date", "Code");

                    b.HasIndex("Date");

                    b.ToTable("Signals");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.Stock", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarginCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScaleCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector17")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector33")
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "AsOfDate");

                    b.HasIndex("AsOfDate");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.TradingCalendar", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("HolidayDivision")
                        .HasColumnType("TEXT");

                    b.HasKey("Date");

                    b.ToTable("TradingCalendars");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.BacktestResult", b =>
                {
                    b.HasOne("TradeAnalyzer.Data.Entities.BacktestRun", "Run")
                        .WithMany("Results")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("TradeAnalyzer.Data.Entities.BacktestRun", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
