<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <SatelliteResourceLanguages>_</SatelliteResourceLanguages>
    <ApplicationIcon>8c15bc8df7b8b13774a3ac6e33d6315f_xxo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="8c15bc8df7b8b13774a3ac6e33d6315f_xxo.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TBird.Core\TBird.Core.csproj" />
    <ProjectReference Include="..\TBird.DB.SQLite\TBird.DB.SQLite.csproj" />
    <ProjectReference Include="..\TBird.DB\TBird.DB.csproj" />
    <ProjectReference Include="..\TBird.Web\TBird.Web.csproj" />
    <ProjectReference Include="..\TBird.Wpf\TBird.Wpf.csproj" />
    <ProjectReference Include="..\_Core\Netkeiba.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="lib\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="lib\path-setting.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
